# ============================================
# DEFAULT PROFILE (DEVELOPMENT)
# ============================================
spring.application.name=ai

# Active profile (dev atau prod)
spring.profiles.active=dev

# Debug mode (development atau production)
debug.mode=development

# Allow proxy/tunnel headers
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto

# Server
server.port=8090